import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/components/providers/session-provider";
import { Toaster } from "sonner";
import { ReduxProvider } from "@/components/providers/redux-provider";
import { LoaderProvider } from "@/components/providers/loader-provider";
import { GlobalLoader } from "@/components/shared/global-loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <ReduxProvider>
            <LoaderProvider>
              <GlobalLoader />
              {children}
              <Toaster
                position="top-right"
                toastOptions={{
                  duration: 4000,
                  style: {
                    background: "#363636",
                    color: "#fff",
                  },
                }}
              />
            </LoaderProvider>
          </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}

// (GlobalLoader is now a client component in components/shared/global-loader.tsx)
